### ISSUE TITLE
How to install gauche as a library?

### ISSUE THREAD

**Issue by wiseodd** [leojklarner/gauche#61]
Hi, thanks for your work! I'm wondering how exactly do I install gauche as a library. It seems that the instructions in the README are only for installing dependencies. Meanwhile, when I do `pip install git+https://github.com/leojklarner/gauche.git`, I get an error

```
error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      error in gauche setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
      [end of output]
```

Thanks!

**Comment by Ryan-Rhys** [comment]
Hi Agustinus,

Thanks for raising the issue! Will be releasing GAUCHE as a package at some point this week, will reply here asap!

Best wishes,
Ryan

**Comment by Ryan-Rhys** [comment]
Hi Agustinus,

Many apologies for the delay! I believe @leojklarner expects to be able to make a release imminently!

Best wishes,
Ryan

**Comment by Ryan-Rhys** [comment]
@wiseodd GAUCHE is now pip installable via:

`pip install gauche`

and we have updated the README accordingly!

**Comment by wiseodd** [comment]
Thanks, I appreciate it!
